services:
  h-prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.5.5327-ls147
    container_name: h-prowlarr
    restart: unless-stopped
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Lisbon
    volumes:
      - ./config:/config
    networks:
      - edge
    labels:
      caddy: http://prowlarr.iedora.com
      caddy.import: authelia
      caddy.reverse_proxy: "{{upstreams 9696}}"

networks:
  edge:
    external: true
